### ISSUE TITLE
Auto-Remove from watch later not working

### ISSUE THREAD

**Issue by mvoelz** [anxdpanic/plugin.video.youtube#993]
### Context

Please provide any relevant information about your setup

* Add-on Version: v7.1.1.1
* Kodi Version: 21.1
* Kodi GUI Language: German
* Operating System: LibreELEC RPi4.aarch64
* Operating System Language: German

------

### Expected Behavior

With the mentioned setting enabled, a video is removed from the watch later list after being watched.

------

### Current Behavior

The video is not removed.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Watch a video from the watch later list.

------

### Log

```

2024-11-22 16:40:04.867 T:1989028   error <general>: Exception in thread 
2024-11-22 16:40:04.867 T:1989028   error <general>: Thread-149
2024-11-22 16:40:04.867 T:1989028   error <general>: :
                                                   
2024-11-22 16:40:04.867 T:1989028   error <general>: 
2024-11-22 16:40:04.867 T:1989028   error <general>: Traceback (most recent call last):
                                                   
2024-11-22 16:40:04.867 T:1989028   error <general>: 
2024-11-22 16:40:04.867 T:1989028   error <general>:   File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
                                                   
2024-11-22 16:40:04.867 T:1989028   error <general>: 
2024-11-22 16:40:04.867 T:1989028   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/monitors/player_monitor.py", line 240, in run
                                                   
2024-11-22 16:40:04.868 T:1989028   error <general>: 
2024-11-22 16:40:04.868 T:1989028   error <general>:     
2024-11-22 16:40:04.868 T:1989028   error <general>: self._provider.on_playlist_x(
2024-11-22 16:40:04.868 T:1989028   error <general>: 
                                                   
2024-11-22 16:40:04.868 T:1989028   error <general>: 
2024-11-22 16:40:04.868 T:1989028   error <general>:   File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_playlist.py", line 363, in process
                                                   
2024-11-22 16:40:04.869 T:1989028   error <general>: 
2024-11-22 16:40:04.869 T:1989028   error <general>:     
2024-11-22 16:40:04.869 T:1989028   error <general>: return _process_remove_video(provider, context, **kwargs)
2024-11-22 16:40:04.869 T:1989028   error <general>: 
                                                   
2024-11-22 16:40:04.869 T:1989028   error <general>: 
2024-11-22 16:40:04.869 T:1989028   error <general>:  
2024-11-22 16:40:04.869 T:1989028    info <general>: Skipped 10 duplicate messages..
2024-11-22 16:40:04.869 T:1989028   error <general>: ^
2024-11-22 16:40:04.870 T:1989028    info <general>: Skipped 49 duplicate messages..
2024-11-22 16:40:04.870 T:1989028   error <general>: 
                                                   
2024-11-22 16:40:04.870 T:1989028   error <general>: 
2024-11-22 16:40:04.870 T:1989028   error <general>: TypeError
2024-11-22 16:40:04.870 T:1989028   error <general>: : 
2024-11-22 16:40:04.870 T:1989028   error <general>: _process_remove_video() got an unexpected keyword argument 'item_name'
2024-11-22 16:40:04.870 T:1989028   error <general>: 

```

------

### Additional Information

I would say it worked in v7.0.9.2.

------

**Comment by MoojMidge** [comment]
Silly mistake that I thought I had already fixed in #971, but missed this line when creating the commit.

If you are able to you can fix this yourself my making the following change, otherwise fix will be available in the next beta version
https://github.com/MoojMidge/plugin.video.youtube/commit/918f775e6e6973cfbb2d165bd6d6ab1fb427df11

Change https://github.com/anxdpanic/plugin.video.youtube/blob/521a0eb5df86bd2823cdaa8cea25ad093ac146e9/resources/lib/youtube_plugin/kodion/monitors/player_monitor.py#L247
From:
```
                        item_name='',
```
To:
```
                        video_name='',
```

**Comment by mvoelz** [comment]
THX that worked for me.
